version: '3.8'

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
      - ./data:/data
      - ./models:/models
    command: >
      mlflow server 
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0 
      --port 5000
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped
