# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /mlflow

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl git python3-dev libffi-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install MLflow
RUN pip install --no-cache-dir mlflow==2.16.0

# Expose MLflow port
EXPOSE 5000

# Start MLflow server
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0", "--port", "5000"]
