version: "3.9"

services:
  mlflow:
    image: ghcr.io/onehungrybird/mlflow:latest
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow-data:/mlflow

  api:
    image: ghcr.io/onehungrybird/creditcard-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: creditcard-api
    restart: unless-stopped
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
      - ./mlflow-data:/mlflow:ro

  # === Prometheus ===
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'  # Allows reload via API

  # === Grafana ===
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana_password  # Change in prod!
      - GF_SERVER_ROOT_URL=http://http://98.80.224.211/:3000  # Optional
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data: