services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
      - ./mlflow/artifacts:/mlflow/artifacts

  api:
    build: .
    container_name: creditcard-api
    restart: unless-stopped
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
