name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push MLflow image
        run: |
          docker build -f Dockerfile.mlflow -t ghcr.io/${{ github.repository_owner }}/mlflow:latest .
          docker push ghcr.io/${{ github.repository_owner }}/mlflow:latest

      - name: Build and push API image
        run: |
          docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/creditcard-api:latest .
          docker push ghcr.io/${{ github.repository_owner }}/creditcard-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/credit-card-fraud-detection1
            docker compose pull
            docker compose up -d --remove-orphans

  post-deploy-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Wait for API
        run: sleep 20

      - name: Test prediction API
        run: |
          curl -X POST http://${{ secrets.EC2_HOST }}:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"feature1": 0.5, "feature2": 1.2, "feature3": 3}'
